export const ENLACES_LINK_ERROR = 'ENLACES_LINK_ERROR';
export const ENLACES_LINK_REQUESTING = 'ENLACES_LINK_REQUESTING';
export const ENLACES_LINK_SUCCESS = 'ENLACES_LINK_SUCCESS';

export const ENLACES_TYPEFORM_REQUESTING = 'ENLACES_TYPEFORM_REQUESTING';
export const ENLACES_TYPEFORM_SUCCESS = 'ENLACES_TYPEFORM_SUCCESS';
export const ENLACES_TYPEFORM_ERROR = 'ENLACES_TYPEFORM_ERROR';
