export const VIDEO_WHATSAPP_REQUESTING = 'VIDEO_WHATSAPP_REQUESTING';
export const VIDEO_WHATSAPP_SUCCESS = 'VIDEO_WHATSAPP_SUCCESS';
export const VIDEO_WHATSAPP_ERROR = 'VIDEO_WHATSAPP_ERROR';

export const VIDEO_ZOOM_REQUESTING = 'VIDEO_ZOOM_REQUESTING';
export const VIDEO_ZOOM_SUCCESS = 'VIDEO_ZOOM_SUCCESS';
export const VIDEO_ZOOM_ERROR = 'VIDEO_ZOOM_ERROR';

export const STORE_VIDEO_USER_REQUESTING = 'STORE_VIDEO_USER_REQUESTING';
export const STORE_VIDEO_USER_SUCCESS = 'STORE_VIDEO_USER_SUCCESS';
export const STORE_VIDEO_USER_ERROR = 'STORE_VIDEO_USER_ERROR';

export const FOCUS_VIDEO = 'FOCUS_VIDEO';

export const SHOW_VIDEO_REQUESTING = 'SHOW_VIDEO_REQUESTING';
export const SHOW_VIDEO_SUCCESS = 'SHOW_VIDEO_SUCCESS';
export const SHOW_VIDEO_ERROR = 'SHOW_VIDEO_ERROR';
